### ISSUE TITLE
Add JSS

### ISSUE THREAD

**Issue by tracker1** [joeshub/css-in-react#2]
Add JSS[0], CSS in JS version(s), Will be similar to the direct styles, but will have some of the advantages of CSS, and other bits.

[0] https://github.com/cssinjs/react-jss

**Comment by joeshub** [comment]
Just added a React JSS button example here 9ba335da7b15b8be4fe8a81f153bd9b8a019db82

I do have one issue that I wonder if there is more elegant solution to. It does not seem like `state` is accessible from a style object, only `props` due to the way `injectSheet` works.

So for this example I've had to bubble up the state to the parent which is not ideal, considering you probably want `Button` to handle the basic state management for you.
